# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

B_distance <- function(x) {
    .Call(`_FPLSDC_B_distance`, x)
}

B_distance_2 <- function(x) {
    .Call(`_FPLSDC_B_distance_2`, x)
}

SumsC <- function(x) {
    .Call(`_FPLSDC_SumsC`, x)
}

colSumsC <- function(x) {
    .Call(`_FPLSDC_colSumsC`, x)
}

grad_dcovU_ratio <- function(a, a2, b, row_sum_b, sum_b, n) {
    .Call(`_FPLSDC_grad_dcovU_ratio`, a, a2, b, row_sum_b, sum_b, n)
}

grad_dcov_U <- function(sgn_a, b, a_u, row_sum_b, sum_b, n) {
    .Call(`_FPLSDC_grad_dcov_U`, sgn_a, b, a_u, row_sum_b, sum_b, n)
}

rowSumsC <- function(x) {
    .Call(`_FPLSDC_rowSumsC`, x)
}

